import type { NextPage } from "next";
import Head from "next/head";
import { useState, useEffect } from "react";
import QRCode from "qrcode";
import { Alert, Container, TextInput } from "@mantine/core";
import Image from "next/image";
import { AiOutlineExclamationCircle } from "react-icons/ai";
import useLocalUrlState from "../hooks/useLocalUrlState";

const Home: NextPage = () => {
  const [qrCodeData, setQrCodeData] = useLocalUrlState<string>({
    key: "qrCodeData",
    defaultValue: "",
  });
  const [qrCodeImage, setQrCodeImage] = useState<string>("");
  const [error, setError] = useState<string>("");

  useEffect(() => {
    if (qrCodeData !== "") {
      QRCode.toDataURL(qrCodeData, function (err, url) {
        if (!err) {
          setError("");
          return setQrCodeImage(url);
        }
        return setError(err.message);
      });
    }
  }, [qrCodeData]);

  return (
    <div>
      <style global jsx>{`
        html,
        body,
        body > div:first-child,
        div#__next,
        div#__next > div {
          height: 100%;
        }
      `}</style>
      <Head>
        <title>QR Code Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container size="lg" style={{ height: "100%" }}>
        <div style={{ height: 50 }}></div>
        <div
          style={{
            display: "flex",
            height: "calc(100% - 50px)",
            alignItems: "center",
            flexDirection: "column",
          }}
        >
          <TextInput
            label="QR Code Data"
            value={qrCodeData}
            onChange={(e) => setQrCodeData(e.currentTarget.value)}
            style={{ width: 300 }}
          />
          <div style={{ height: 50, width: "100%" }}>
            {error !== "" && (
              <Alert
                icon={<AiOutlineExclamationCircle size={16} />}
                title="Error!"
                color="red"
              >
                {error}
              </Alert>
            )}
          </div>
          <div
            style={{
              width: "100%",
              height: "calc(100% - 150px)",
              position: "relative",
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            {qrCodeImage !== "" && (
              <Image
                src={qrCodeImage}
                alt="qr code image"
                layout="fixed"
                width={320}
                height={320}
              ></Image>
            )}
          </div>
        </div>
      </Container>
    </div>
  );
};

export default Home;
